#!/usr/bin/env python3
import shutil
from datetime import datetime
import os
from pytz import timezone
from shutil import copyfile
import subprocess
from jinja2 import Template

def main():
    if not shutil.which('aoc'):
        raise(ValueError('AOC commandline util not found. Get it from https://github.com/scarvalhojr/aoc-cli'))
    eastern = timezone('US/Eastern')
    now = datetime.now(eastern)
    yyyy = now.year
    dd = str(now.day).rjust(2, '0')
    date_slug = f'{yyyy}/{dd}'
    os.makedirs(date_slug, exist_ok=True)
    dest_path = f'{date_slug}/solution.py'
    if os.path.isfile(dest_path):
        print(f'File {dest_path} already exists. Not overwriting.')
    else:
        # Render the j2 file as a new usable script and populate the date in the header comment
        with open('./solution.py.j2') as t:
            rendered = Template(t.read()).render(DD=dd, YYYY=yyyy)
        with open(dest_path, "w") as fh:
            fh.write(rendered)
        os.chmod(dest_path, 0o755)

    # Get the puzzle's readme
    if os.path.isfile(f'{date_slug}/puzzle.md'):
        print(f'Already downloaded {date_slug}/puzzle.md')
    else:
        subprocess.run('aoc', cwd=date_slug)

    # Get the puzzle's input
    if os.path.isfile(f'{date_slug}/input'):
        print(f'Already downloaded {date_slug}/input')
    else:
        subprocess.run(['aoc', 'd'], cwd=date_slug)


if __name__ == "__main__":
    main()
